/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and configuration probe.
         * @description Unauthenticated. Reports which backend implementation is answering and whether it is
         *     configured well enough to talk to Meteroid. The contract suite calls this first so a
         *     misconfigured run fails with a clear message instead of a wall of 5xx.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a demo workspace (and a Meteroid customer).
         * @description Creates a brand-new Meteroid customer with a generated, unique alias and returns a session
         *     token bound to it. Every demo run gets its own customer; the same Meteroid API key is reused
         *     indefinitely. No subscription exists yet — the workspace starts unsubscribed, and the
         *     frontend drives the visitor to `POST /api/checkout`.
         *
         *     Meteroid's `CustomerCreateRequest` requires `name`, `invoicing_emails`, `currency` and
         *     `custom_taxes`. The backend fills them from the (optional) request body plus generated
         *     defaults, and takes the currency from `SCRIBE_DEFAULT_CURRENCY`. **That currency must equal
         *     the currency of the seeded plans** — Meteroid rejects a checkout whose customer and plan
         *     version disagree — so a mismatch is reported as `CATALOG_NOT_SEEDED` at checkout time.
         *
         *     The request body is optional: no body, an empty body and `{}` are all equivalent.
         *
         *     **SDK surface:** Rust `client.customers().create_customer(CustomerCreateRequest { .. })`;
         *     Java `new Customers(httpClient).createCustomer(request)`.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current workspace, its subscription and its plan.
         * @description Resolves the session's customer, its most relevant subscription, and the plan that
         *     subscription is on. `subscription` and `plan` are both `null` for a workspace that has
         *     never checked out.
         *
         *     Subscriptions are fetched with `GET /api/v1/subscriptions?customer_id=<alias>`, which accepts
         *     a customer id *or* alias, so no extra id lookup is needed.
         *
         *     **Which subscription is "the most relevant" one** is pinned down here so every backend
         *     picks the same one, and so `GET /api/usage` and `POST /api/transcriptions` agree with this
         *     endpoint: ask Meteroid with `order_by=created_at.desc`, take the first subscription whose
         *     status is `ACTIVE` or `TRIAL_ACTIVE`, and otherwise the first of the list (the most
         *     recently created, whatever its status).
         *
         *     The seeded catalog is consulted only when a subscription exists — it is what maps
         *     Meteroid's `plan_id`/`plan_name` onto this contract's `plan_code`. A workspace that has
         *     never subscribed therefore answers even on a tenant whose catalog is unreachable, while a
         *     subscribed one reports `CATALOG_NOT_SEEDED`; that is deliberate, because this is the
         *     frontend's boot call and an unseeded tenant should be visible immediately rather than
         *     first surfacing at checkout.
         *
         *     **SDK surface:** Rust `client.customers().get_customer(alias)` and
         *     `client.subscriptions().list_subscriptions(..)`; Java `getCustomer` / `listSubscriptions`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The pricing table.
         * @description The three seeded Scribe plans, each resolved to its latest published (non-draft) version,
         *     with a flattened summary of that version's price components. Ordered `free`, `pro`, `scale`.
         *
         *     Meteroid plans have no user-supplied `code`, so the backend resolves each plan by its exact
         *     seeded **name** (see `examples/CATALOG.md`) and maps it onto the stable `plan_code` this
         *     contract uses. `GET /api/v1/plans?search=…` is a fuzzy name match, so the backend must
         *     additionally require `name == <seeded name>` exactly. A missing or unpublished plan is a
         *     seeding error, not a runtime condition: the backend returns `CATALOG_NOT_SEEDED` naming the
         *     plan it could not resolve.
         *
         *     `GET /api/v1/plans` already returns full `Plan` objects, including `version_id` and
         *     `price_components`, so the pricing table needs no per-plan follow-up call; the marketing
         *     bullets in `features` come from `GET /api/v1/plan-versions/{version_id}/entitlements`, whose
         *     `ResolvedEntitlement.feature` carries the feature `code`.
         *
         *     **SDK surface:** Rust `client.plans().list_plans(..)` and
         *     `client.plans().list_plan_version_entitlements(plan_version_id)`; Java `listPlans` /
         *     `listPlanVersionEntitlements`.
         */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a hosted checkout for a plan.
         * @description Creates a Meteroid checkout session for the workspace's customer against the requested
         *     plan's published version and returns the hosted checkout URL to redirect to. Used both for
         *     the first subscription and for upgrades — Meteroid decides the `checkout_type`.
         *
         *     A Meteroid checkout session may legitimately carry a null `checkout_url` (non-self-serve
         *     checkout types). This contract treats that as a hard failure for the demo's purposes and
         *     returns `CHECKOUT_UNAVAILABLE` rather than handing the frontend a null it cannot use.
         *
         *     Meteroid's `CreateCheckoutSessionRequest.customer_id` accepts a customer id *or* alias, so
         *     the backend passes the workspace alias straight through.
         *
         *     **SDK surface:** Rust `client.checkout_sessions().create_checkout_session(req)`;
         *     Java `createCheckoutSession(request)`. The response is `{ session: CheckoutSession }`.
         */
        post: operations["createCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Normalized entitlements for feature gating.
         * @description The workspace's effective entitlements, one entry per feature, normalized into an explicitly
         *     tagged union the frontend can switch on. This is the view the SPA gates the UI with and the
         *     same view `POST /api/transcriptions` enforces server-side.
         *
         *     Meteroid's `EffectiveEntitlementValue` is a `oneOf` discriminated on `type`
         *     (`BOOLEAN` / `METERED` / `CONFIG`); this contract keeps that discriminator, flattens the
         *     metered `spec`+`usage` pair into one object, and preserves every decimal as a string.
         *
         *     Note that Meteroid's `MeteredEntitlementUsage` declares *no* required properties, so
         *     `consumed`, `remaining` and `reset_at` may be absent on the wire. Backends normalize an
         *     absent value to an explicit `null` here, per this contract's response nullability rule.
         *
         *     Expected feature codes for the seeded Scribe catalog: `transcription_minutes` (metered),
         *     `sso` (boolean), `retention_days` (config/number), `seats` (config/number). A workspace with
         *     no subscription still returns the feature-level defaults Meteroid resolves, which may be an
         *     empty list.
         *
         *     **SDK surface:** Rust `client.customers().get_effective_entitlements(alias)`;
         *     Java `getEffectiveEntitlements(idOrAlias)`. The response is `{ data: EffectiveEntitlement[] }`.
         */
        get: operations["listEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transcriptions created in this workspace.
         * @description Demo-local history, newest first. Backends keep this in memory; it is not persisted and it
         *     resets when the process restarts. Meteroid is the source of truth for *usage*, not for the
         *     application objects that produced it.
         */
        get: operations["listTranscriptions"];
        put?: never;
        /**
         * Transcribe audio — the metered action.
         * @description The centerpiece of the demo. In order:
         *
         *     1. Read the workspace's effective entitlements and find `transcription_minutes`.
         *     2. If the entitlement is missing or `enabled` is `false` → **403 `FEATURE_NOT_ENTITLED`**.
         *        Note that "missing" is ambiguous per-request: an unsubscribed workspace and an unseeded
         *        tenant both produce an empty entitlement list. Backends resolve the ambiguity once at
         *        startup with `GET /api/v1/features/{code}` for the four seeded codes, and report an
         *        unseeded tenant as `CATALOG_NOT_SEEDED` rather than letting it masquerade as a 403.
         *
         *        If the entitlement is *present but not `METERED`* — the feature exists in the tenant but
         *        was created as boolean or config in the dashboard — that is a seeding mistake, not a
         *        customer-facing paywall, and it is **503 `CATALOG_NOT_SEEDED`**. Never a 403: an
         *        operator error must not look like "your plan doesn't include that".
         *     3. If it has a `limit` and the requested minutes exceed the remaining balance →
         *        **402 `QUOTA_EXHAUSTED`**, with the live quota snapshot and the plan to upgrade to
         *        echoed back in the error body so the frontend can render an upgrade prompt without a
         *        second round trip. A `null` limit means unlimited and never trips this branch.
         *
         *        The remaining balance is Meteroid's `remaining`; because Meteroid may supply a `limit`
         *        with no counter yet, backends fall back to `limit - consumed` when `remaining` is null,
         *        and to `limit` when both are null. All three are decimal strings and the arithmetic must
         *        be exact decimal arithmetic (`rust_decimal`, `BigDecimal`) — never binary floating point,
         *        which is how a 0.1-minute clip eventually bills wrong.
         *     4. Otherwise produce the (fake) transcript and report consumption to Meteroid by ingesting
         *        one event with `code: transcription_minutes`, the workspace's customer alias, and
         *        `properties.minutes` set to the billed minutes as a decimal string.
         *
         *     Because step 2 turns a missing or disabled entitlement into a 403, a 201 always carries a
         *     `quota` — an unlimited entitlement is reported as `unlimited: true` with `limit`,
         *     `remaining` and `reset_at` null, never as an absent quota.
         *
         *     Meteroid usage counters are eventually consistent: `quota` in the 201 body is the backend's
         *     optimistic local projection of the entitlement it just read, and `GET /api/usage` may lag by
         *     a few seconds. Callers must not treat the two as transactionally consistent.
         *
         *     The ingest is a batch call (`{ events: [ … ] }`, 1–100 events); the demo sends exactly one,
         *     with `timestamp` set to now — Meteroid rejects timestamps outside `24h ago .. 1h ahead`
         *     unless `allow_backfilling` is set, which this demo never does.
         *
         *     **SDK surface:** Rust `client.customers().get_effective_entitlements(alias)` then
         *     `client.events().ingest_events(IngestEventsRequest { events, .. })`;
         *     Java `getEffectiveEntitlements` then `ingestEvents`.
         */
        post: operations["createTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current-period usage for the workspace.
         * @description Usage for the current billing period, per billable metric, straight from Meteroid. Queried
         *     by subscription when the workspace has one (so the period matches the billing cycle),
         *     falling back to the customer-scoped query otherwise. `scope` says which happened.
         *
         *     The two Meteroid endpoints differ in an important way:
         *
         *     * `GET /api/v1/usage/subscription/{id}` takes `start_date`/`end_date` as **optional** query
         *       params; omitting them makes Meteroid use the subscription's current billing period. The
         *       backend omits them, so `period_start`/`period_end` are Meteroid's, not the demo's.
         *     * `GET /api/v1/usage/customer/{id_or_alias}` **requires** `start_date` and `end_date`. With
         *       no subscription there is no billing period to borrow, so the backend supplies the current
         *       calendar month (first of the month .. today, UTC) and echoes exactly that back. Treat a
         *       `customer`-scoped period as a demo convention, not a billing period.
         *
         *     `total_value` and every grouped `value` are decimal strings.
         *
         *     **SDK surface:** Rust `client.usage().get_subscription_usage(..)` /
         *     `client.usage().get_customer_usage(..)`; Java `getSubscriptionUsage` / `getCustomerUsage`.
         */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a customer-portal token.
         * @description Issues a short-lived Meteroid customer-portal token for the workspace's customer, so the
         *     visitor can manage their payment method and download invoices without the demo implementing
         *     any of it. The frontend opens `portal_url` with the `token`.
         *
         *     Meteroid documents the valid lifetime as 60..2592000 seconds but types the field only as a
         *     non-negative int32, so the backend validates the range itself and returns `BAD_REQUEST`
         *     rather than forwarding a value Meteroid would reject. The request body is optional: no body,
         *     an empty body and `{}` all mean "use Meteroid's default of 86400 seconds".
         *
         *     **SDK surface:** Rust `client.customers().create_portal_token(alias, req)`;
         *     Java `createPortalToken(idOrAlias, request)`. The response is `{ token, portal_url }` —
         *     Meteroid returns no expiry, so `expires_in_seconds` below is the value the backend asked for.
         */
        post: operations["createPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoices for the workspace.
         * @description The workspace customer's invoices, newest first. A fresh workspace has none, and a workspace
         *     that just checked out usually has a `DRAFT` one.
         *
         *     Amounts are integers in the currency's **minor units** (cents), matching Meteroid.
         *
         *     Fetched with `GET /api/v1/invoices?customer_id=<alias>&order_by=invoice_date.desc`;
         *     `customer_id` accepts an id or an alias, and `limit` below maps onto Meteroid's `per_page`
         *     (which also caps at 100).
         *
         *     **SDK surface:** Rust `client.invoices().list_invoices(..)`; Java `listInvoices(options)`.
         */
        get: operations["listInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/meteroid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signed webhook receiver.
         * @description Receives Meteroid webhook events, verifying the Standard Webhooks signature over the **raw**
         *     request body before parsing it. `svix-*` headers are accepted as aliases for `webhook-*`;
         *     timestamps outside a five-minute tolerance are rejected.
         *
         *     Verification failures return **400 `WEBHOOK_SIGNATURE_INVALID`** — deliberately not 401,
         *     which this contract reserves for a bad session token.
         *
         *     The demo handles `invoice.*` and `subscription.*` events by logging them and surfacing the
         *     last few in the frontend's activity feed; every other event type is acknowledged with
         *     `handled: false`. Unknown event types are never an error — new Meteroid event types must not
         *     break a receiver.
         *
         *     **The event envelope is not part of `spec/openapi.json`** — webhook endpoints and their
         *     payloads are configured in the dashboard and Meteroid publishes no schema for them, so the
         *     body schema below is a best-effort description with **no required properties**. A receiver
         *     must never reject a correctly signed body for its shape: parse what it recognizes, ack the
         *     rest with `handled: false`. `400` is reserved for a failed/absent signature and for a body
         *     that is not JSON at all.
         *
         *     **SDK surface:** Rust `meteroid_rs::webhooks::Webhook::new(secret)?.verify(raw_body, &headers)`;
         *     Java `new Webhook(secret).verify(payload, headers)`. Both SDKs also expose a *signer*
         *     (`Webhook::sign` / `Webhook.sign(msgId, timestamp, payload)`), which is how the contract
         *     suite exercises this endpoint with validly signed payloads and no live tenant.
         *
         *     Verification runs over the **raw bytes** of the body. A backend that re-serializes the parsed
         *     JSON before verifying will fail on any payload whose key order or spacing differs.
         */
        post: operations["receiveMeteroidWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Machine-readable error identifier. Clients switch on this, never on `message`.
         *
         *     * `BAD_REQUEST` — malformed body or query.
         *     * `UNAUTHORIZED` — missing/invalid session token.
         *     * `NOT_FOUND` — unmatched route. No operation in this contract takes a path or lookup
         *       parameter, so this cannot arise from a documented operation; it exists so that a 404 from
         *       a typo still arrives in the standard envelope.
         *     * `NO_SUBSCRIPTION` — the operation needs an active subscription and the workspace has none.
         *       Reserved: no operation in this contract currently requires one (`GET /api/usage` falls
         *       back to the customer scope instead of failing).
         *     * `FEATURE_NOT_ENTITLED` — the feature is not granted, or its entitlement is disabled.
         *     * `QUOTA_EXHAUSTED` — granted but used up; `quota` is populated.
         *     * `CHECKOUT_UNAVAILABLE` — Meteroid produced no hosted checkout URL for this request.
         *     * `CATALOG_NOT_SEEDED` — a required catalog object is missing from the tenant.
         *     * `WEBHOOK_SIGNATURE_INVALID` — webhook signature verification failed.
         *     * `UPSTREAM_UNAUTHORIZED` — the backend's Meteroid API key was rejected.
         *     * `UPSTREAM_ERROR` — Meteroid errored or was unreachable.
         *     * `RATE_LIMITED` — Meteroid (or the demo) is throttling.
         *     * `INTERNAL` — unexpected backend failure.
         * @enum {string}
         */
        ErrorCode: "BAD_REQUEST" | "UNAUTHORIZED" | "NOT_FOUND" | "NO_SUBSCRIPTION" | "FEATURE_NOT_ENTITLED" | "QUOTA_EXHAUSTED" | "CHECKOUT_UNAVAILABLE" | "CATALOG_NOT_SEEDED" | "WEBHOOK_SIGNATURE_INVALID" | "UPSTREAM_UNAUTHORIZED" | "UPSTREAM_ERROR" | "RATE_LIMITED" | "INTERNAL";
        /**
         * @description The single error envelope every non-2xx response in this contract uses. `quota` and
         *     `upgrade_plan_code` are typed rather than free-form so the contract suite can assert on the
         *     quota-exhausted path. Both are **always present** and are `null` for errors where they do
         *     not apply — a client never has to distinguish an absent key from a null one.
         */
        Error: {
            code: components["schemas"]["ErrorCode"];
            /**
             * @description Human-readable explanation. Safe to show in the demo UI; never parsed.
             * @example Missing Authorization: Bearer <session_token> header.
             */
            message: string;
            /** @description Live quota snapshot. Populated only for `QUOTA_EXHAUSTED`. */
            quota: components["schemas"]["QuotaSnapshot"] | null;
            /**
             * @description The plan the frontend should offer as the fix. Populated for `QUOTA_EXHAUSTED` and
             *     `FEATURE_NOT_ENTITLED`; `null` for every other error code.
             *
             *     **Resolution rule**, fixed here so that every backend offers the same upsell: it is one
             *     plan up the ladder `free` → `pro` → `scale` from the workspace's current plan, where
             *     "current plan" is the plan of the subscription `GET /api/me` would report.
             *
             *     * no subscription, or a subscription on a plan outside the Scribe catalog → `pro`
             *     * `free` → `pro`; `pro` → `scale`; `scale` → `null` (nothing left to sell)
             *     * the lookup itself failing → `null`
             *
             *     That last case matters: this field decorates an error response, so a failure while
             *     resolving it must never replace the error the caller actually hit. Backends resolve it
             *     lazily, on the `402`/`403` paths only, so the successful path stays at two Meteroid
             *     calls.
             */
            upgrade_plan_code: components["schemas"]["PlanCode"] | null;
        };
        /**
         * @description Stable identifier for a Scribe plan, used everywhere in this contract. Meteroid plans carry
         *     no user-supplied code, so backends map each of these onto the exact seeded plan **name**
         *     documented in `examples/CATALOG.md`.
         * @enum {string}
         */
        PlanCode: "free" | "pro" | "scale";
        /**
         * @description An exact decimal, serialized as a string — matching Meteroid's `format: decimal`. Never a
         *     JSON number.
         * @example 60
         * @example 3.5
         * @example 0
         */
        Decimal: string;
        /**
         * @description ISO 4217 currency code, uppercase. Meteroid types this as a closed enum of ~160 codes on
         *     customers and subscriptions, but as a bare string on `Plan`; this contract validates the
         *     shape only and passes through whatever Meteroid returned.
         * @example USD
         */
        Currency: string;
        Health: {
            /** @enum {string} */
            status: "ok";
            /**
             * @description Which implementation is answering. Used in contract-suite reporting.
             * @enum {string}
             */
            backend: "rust" | "java" | "typescript" | "python" | "go";
            /**
             * @description True when `METEROID_API_KEY` and `METEROID_BASE_URL` are set. False means every
             *     Meteroid-backed operation will fail with `UPSTREAM_UNAUTHORIZED`.
             */
            meteroid_configured: boolean;
            /** @description Backend build version, if it has one. */
            version: string | null;
        };
        /**
         * @description All fields optional; the backend generates whatever is not supplied. Omitting a key, sending
         *     it as `null`, and sending no body at all are equivalent.
         */
        CreateSessionRequest: {
            /** @description Display name for the workspace, also used as the Meteroid customer name. */
            workspace_name?: string | null;
            /**
             * Format: email
             * @description Invoicing email for the Meteroid customer — Meteroid requires a non-empty
             *     `invoicing_emails` array, so the backend generates a demo address when this is omitted.
             */
            email?: string | null;
        };
        /**
         * @description A demo workspace — one-to-one with a Meteroid customer.
         *
         *     There is deliberately **no `created_at`**: Meteroid's `Customer` schema carries no
         *     creation timestamp (check `spec/openapi.json` — it has neither `created_at` nor
         *     `updated_at`), so `GET /api/me` would have nothing truthful to put there. Every field
         *     below is a 1:1 projection of a Meteroid customer field.
         */
        Workspace: {
            /**
             * @description Workspace identifier. Equal to `customer_alias`.
             * @example scribe-demo-8f2a1c
             */
            id: string;
            name: string;
            /**
             * @description Meteroid customer id.
             * @example cus_7n42DGM5Tflk9n8mt7Fhc7
             */
            customer_id: string;
            /**
             * @description Meteroid customer alias. The demo uses the alias — not the id — as the `customer_id`
             *     field of ingested events, to show that events can reference your own identifier.
             * @example scribe-demo-8f2a1c
             */
            customer_alias: string;
            /**
             * @description The customer's billing currency, from `SCRIBE_DEFAULT_CURRENCY`. Must match the seeded
             *     plans' currency or checkout will fail.
             */
            currency: components["schemas"]["Currency"];
        };
        CreateSessionResponse: {
            /** @description Send as `Authorization: Bearer <session_token>`. Opaque. */
            session_token: string;
            workspace: components["schemas"]["Workspace"];
        };
        /**
         * @description Mirrors Meteroid's subscription status enum verbatim.
         * @enum {string}
         */
        SubscriptionStatus: "PENDING_ACTIVATION" | "PENDING_CHARGE" | "TRIAL_ACTIVE" | "ACTIVE" | "TRIAL_EXPIRED" | "PAUSED" | "SUSPENDED" | "CANCELLED" | "ABORTED" | "COMPLETED" | "SUPERSEDED" | "ERRORED";
        /**
         * @description A projection of Meteroid's `Subscription`. Every field maps 1:1 onto one Meteroid field —
         *     nothing here is derived, so the two can never drift.
         */
        Subscription: {
            /** @example sub_7n42DGM5Tflk9n8mt7Fhc7 */
            id: string;
            status: components["schemas"]["SubscriptionStatus"];
            /**
             * @description Null when the subscription is on a plan outside the seeded Scribe catalog — possible if
             *     an operator subscribes the customer by hand. Resolved by matching Meteroid's `plan_name`
             *     against the seeded names, since Meteroid subscriptions carry no plan code.
             */
            plan_code: components["schemas"]["PlanCode"] | null;
            /** @description Meteroid's `plan_name`, verbatim. */
            plan_name: string;
            plan_version_id: string;
            currency: components["schemas"]["Currency"];
            /**
             * Format: date
             * @description Meteroid's `current_period_start` — a date, not a timestamp.
             */
            current_period_start: string;
            /**
             * Format: date
             * @description Meteroid's `current_period_end`. Null for an open-ended period.
             */
            current_period_end: string | null;
            /**
             * Format: int32
             * @description Meteroid's `trial_duration`, in days; null when the subscription has no trial. This is a
             *     *duration*, deliberately not a computed trial end date — Meteroid exposes no trial-end
             *     field, and deriving one from `start_date` would silently disagree with Meteroid's own
             *     anchoring rules.
             */
            trial_duration_days: number | null;
            /** Format: date-time */
            created_at: string;
        };
        MeResponse: {
            workspace: components["schemas"]["Workspace"];
            /** @description The workspace's active subscription, or the most recent one. Null if never subscribed. */
            subscription: components["schemas"]["Subscription"] | null;
            /** @description The plan `subscription` is on, resolved from the catalog. Null when there is no subscription. */
            plan: components["schemas"]["Plan"] | null;
        };
        /**
         * @description Mirrors Meteroid's billing period enum.
         * @enum {string}
         */
        BillingPeriod: "MONTHLY" | "QUARTERLY" | "SEMIANNUAL" | "ANNUAL";
        /**
         * @description Which Meteroid fee type a price component is — the `type` tag of Meteroid's `Fee` union.
         *     `RATE` is a flat recurring price, `USAGE` is pay-as-you-go on a metric, `CAPACITY` is a
         *     committed bundle with overage, `SLOT` is per-seat.
         * @enum {string}
         */
        PriceKind: "RATE" | "SLOT" | "CAPACITY" | "USAGE" | "EXTRA_RECURRING" | "ONE_TIME";
        /**
         * @description The pricing model of a `USAGE` component, mirroring Meteroid's `PlanUsagePricingModel` tag.
         *     Only `PER_UNIT` has a single unit price; for every other model `unit_amount` is `null` and
         *     the frontend renders the model name instead of a number.
         * @enum {string}
         */
        UsagePricingModel: "PER_UNIT" | "TIERED" | "VOLUME" | "PACKAGE" | "MATRIX";
        /**
         * @description A flattened, display-oriented summary of one Meteroid price component. Deliberately lossy —
         *     it exists to render a pricing table, not to reprice anything. Fields that do not apply to
         *     the component's `kind` are `null`.
         *
         *     **Flattening rules** (identical in every backend, so the contract suite can compare them):
         *
         *     * Meteroid's `PriceComponent.fee` is nullable. A component with no fee has no price to show
         *       and is **omitted** from `Plan.prices` entirely.
         *     * `RATE` and `SLOT` fees carry `rates: TermRate[]` — one price per billing term. The backend
         *       picks the term matching the plan's own cadence when present, else the first entry, and
         *       reports that term in `cadence`. Other terms are dropped: this is a pricing *table*.
         *     * `CAPACITY` fees carry `thresholds: CapacityThreshold[]`. The backend takes the first
         *       threshold: `amount` = its `price`, `included_amount` = its `included_amount`,
         *       `unit_amount` = its `per_unit_overage`.
         *     * `EXTRA_RECURRING` reports `unit_price` as `amount`; its `quantity` is dropped.
         *     * `USAGE` and `CAPACITY` fees name their metric by `metric_id` only, so `unit_name` is
         *       resolved through the same `metric_id` → `metric_code` map the entitlement view uses, and
         *       is `null` when the metric cannot be resolved.
         */
        PlanPrice: {
            component_id: string;
            /**
             * @example Pro monthly
             * @example Included transcription minutes
             */
            name: string;
            kind: components["schemas"]["PriceKind"];
            /** @description Billing cadence. Null for `ONE_TIME`, which has no cadence in Meteroid. */
            cadence: components["schemas"]["BillingPeriod"] | null;
            /**
             * @description Recurring or one-off price for `RATE` / `SLOT` (per slot) / `EXTRA_RECURRING` /
             *     `ONE_TIME`, or the committed price of the first threshold for `CAPACITY`. Null for
             *     `USAGE`.
             */
            amount: components["schemas"]["Decimal"] | null;
            /**
             * @description Price per unit: the `PER_UNIT` rate for `USAGE`, or `per_unit_overage` for `CAPACITY`.
             *     Null for every other kind, and for a `USAGE` component whose `pricing_model` is not
             *     `PER_UNIT`.
             */
            unit_amount: components["schemas"]["Decimal"] | null;
            /**
             * @description Units included before overage, for `CAPACITY`. Meteroid types this as an integer count;
             *     it is carried as a decimal string here so that every quantity in this contract has one
             *     representation. Null for every other kind.
             */
            included_amount: components["schemas"]["Decimal"] | null;
            /**
             * @description What a unit is called — the resolved metric code for `USAGE`/`CAPACITY`, the fee's
             *     `slot_unit_name` for `SLOT`. Null for the other kinds and when a metric code cannot be
             *     resolved.
             * @example transcription_minutes
             * @example seat
             */
            unit_name: string | null;
            /** @description Set for `USAGE` components; null for every other kind. */
            pricing_model: components["schemas"]["UsagePricingModel"] | null;
        };
        /** @description A seeded Scribe plan, resolved to its latest published version. */
        Plan: {
            code: components["schemas"]["PlanCode"];
            /**
             * @description The plan's exact Meteroid name — the key the backend resolved it by.
             * @example Scribe Pro
             */
            name: string;
            description: string | null;
            plan_id: string;
            /**
             * @description Meteroid's `Plan.version_id` for the active (published) version. This is what
             *     `POST /api/checkout` sends as `plan_version_id`.
             */
            plan_version_id: string;
            /** Format: int32 */
            version: number;
            currency: components["schemas"]["Currency"];
            /** @description True when Meteroid's `plan_type` is `FREE`. */
            is_free: boolean;
            /**
             * Format: int32
             * @description `trial.duration_days` from Meteroid's `TrialConfig`; null when the plan has no trial.
             */
            trial_days: number | null;
            prices: components["schemas"]["PlanPrice"][];
            /**
             * @description Marketing bullets for the pricing table, derived from the plan version's entitlements
             *     (`GET /api/v1/plan-versions/{id}/entitlements`) so the pricing page and the enforcement
             *     path cannot drift apart.
             */
            features: components["schemas"]["PlanFeatureLine"][];
        };
        /** @description One entitlement of a plan version, rendered for humans. */
        PlanFeatureLine: {
            /**
             * @example transcription_minutes
             * @example sso
             * @example retention_days
             * @example seats
             */
            feature_code: string;
            /**
             * @example 600 transcription minutes / month
             * @example SSO included
             * @example 90-day retention
             */
            label: string;
        };
        PlanListResponse: {
            /** @description Ordered cheapest-first — `free`, `pro`, `scale`. */
            plans: components["schemas"]["Plan"][];
        };
        CreateCheckoutRequest: {
            plan_code: components["schemas"]["PlanCode"];
            /** @description Optional promotion code, passed straight through to Meteroid. */
            coupon_code?: string | null;
        };
        CreateCheckoutResponse: {
            /**
             * Format: uri
             * @description Hosted Meteroid checkout page. Never null — a null URL from Meteroid becomes a
             *     `CHECKOUT_UNAVAILABLE` error instead.
             */
            checkout_url: string;
            checkout_session_id: string;
            plan_code: components["schemas"]["PlanCode"];
            plan_version_id: string;
            /**
             * Format: date-time
             * @description Meteroid's `expires_at`. Null means the session does not expire.
             */
            expires_at: string | null;
        };
        /**
         * @description Mirrors Meteroid's reset-period discriminator.
         * @enum {string}
         */
        ResetPeriodType: "BILLING_CYCLE" | "CALENDAR" | "FIXED_WINDOW" | "SLIDING_WINDOW" | "NEVER";
        /**
         * @description Mirrors Meteroid's `CalendarUnit` enum verbatim.
         * @enum {string}
         */
        CalendarUnit: "HOUR" | "DAY" | "WEEK" | "MONTH" | "YEAR";
        /**
         * @description Flattened reset period. Meteroid models this as its own tagged union
         *     (`BillingCycleResetPeriod`, `CalendarResetPeriod`, `FixedWindowResetPeriod`,
         *     `SlidingWindowResetPeriod`, `NeverResetPeriod`); every variant beyond the tag carries at
         *     most an `interval`+`unit` pair, so this contract keeps the tag and makes both fields
         *     nullable rather than nesting a second union inside the entitlement union.
         *
         *     `interval` and `unit` are non-null together, for `CALENDAR`, `FIXED_WINDOW` and
         *     `SLIDING_WINDOW`, and both null for `BILLING_CYCLE` and `NEVER`.
         */
        ResetPeriod: {
            type: components["schemas"]["ResetPeriodType"];
            /**
             * Format: int32
             * @description Null for `BILLING_CYCLE` and `NEVER`. Meteroid's own minimum is 0, not 1.
             */
            interval: number | null;
            /** @description Calendar unit for the interval. Null for `BILLING_CYCLE` and `NEVER`. */
            unit: components["schemas"]["CalendarUnit"] | null;
        };
        /**
         * @description The consumption state of one metered entitlement at a point in time. Returned inside
         *     successful metered actions and inside `QUOTA_EXHAUSTED` errors, so the frontend renders the
         *     same widget either way. All amounts are decimal strings.
         *
         *     When `unlimited` is `true`, `limit` and `remaining` are both `null` and `consumed` may still
         *     carry a running total.
         */
        QuotaSnapshot: {
            /** @example transcription_minutes */
            feature_code: string;
            /** @description The entitlement's kill switch. False means the feature is off entirely. */
            enabled: boolean;
            /** @description Cap for the period. Null means unlimited. */
            limit: components["schemas"]["Decimal"] | null;
            /** @description Amount consumed in the current period. Null when Meteroid has no counter yet. */
            consumed: components["schemas"]["Decimal"] | null;
            /**
             * @description Amount left in the period. Null when `limit` is null (unlimited). When Meteroid supplies
             *     a `limit` but no `remaining`, backends fill this in as `limit - consumed` (or `limit`
             *     when `consumed` is also null), so a limited entitlement always reports a balance here —
             *     it is the number the quota check compares against.
             */
            remaining: components["schemas"]["Decimal"] | null;
            /**
             * Format: date-time
             * @description When the counter next resets, from Meteroid's `MeteredEntitlementUsage.reset_at`. Null
             *     for `NEVER` reset periods and whenever Meteroid does not supply one.
             */
            reset_at: string | null;
            /** @description Convenience mirror of `limit == null`, so clients need not special-case null. */
            unlimited: boolean;
        };
        /**
         * @description A numeric config value. Meteroid's `NumberConfigValue.value` is `type: string,
         *     format: decimal`, so this stays a decimal string — `retention_days: "90"`, not `90`.
         */
        NumberConfigValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "NUMBER";
            value: components["schemas"]["Decimal"];
        };
        BooleanConfigValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "BOOLEAN";
            value: boolean;
        };
        TextConfigValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "TEXT";
            value: string;
        };
        JsonConfigValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "JSON";
            /**
             * @description Arbitrary JSON, passed through unchanged — any JSON value, `null` included. Deserialize
             *     it as an untyped JSON value (`serde_json::Value`, `JsonNode`), never as a struct.
             */
            value: unknown;
        };
        /**
         * @description A typed configuration value, tagged by `kind`. Meteroid's `ConfigValueType` also has `MAP`
         *     and `SELECT`; backends normalize `MAP` onto `JSON` and `SELECT` onto `TEXT`, so clients only
         *     ever see the four kinds below.
         *
         *     Meteroid discriminates its own `ConfigValue` on `kind` but omits that property from the
         *     variant schemas; this contract declares it explicitly as a `const`, so the union is
         *     deserializable by a strict internally-tagged decoder without any generator-specific
         *     discriminator support.
         */
        ConfigValue: components["schemas"]["NumberConfigValue"] | components["schemas"]["BooleanConfigValue"] | components["schemas"]["TextConfigValue"] | components["schemas"]["JsonConfigValue"];
        /** @description An on/off feature — Scribe uses this for `sso`. */
        BooleanEntitlementValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "BOOLEAN";
            enabled: boolean;
        };
        /**
         * @description A consumption-limited feature — Scribe uses this for `transcription_minutes`. Flattens
         *     Meteroid's `spec` (limit, reset period, kill switch) and `usage` (consumed, remaining,
         *     reset_at) into one object. All amounts are decimal strings.
         *
         *     Meteroid's `MeteredEntitlementUsage` requires none of its three properties, so `consumed`,
         *     `remaining` and `reset_at` arrive absent for an entitlement with no counter yet; they are
         *     normalized to explicit nulls here.
         */
        MeteredEntitlementValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "METERED";
            /** @description Meteroid's per-entitlement kill switch. False means the feature is off. */
            enabled: boolean;
            /** @description Cap for the period. Null means unlimited. */
            limit: components["schemas"]["Decimal"] | null;
            /** @description Consumed in the current period. Null when Meteroid has no counter yet. */
            consumed: components["schemas"]["Decimal"] | null;
            /**
             * @description Remaining in the current period. Null **only** when `limit` is null (unlimited).
             *
             *     This is the same derived balance `QuotaSnapshot.remaining` carries, and it is derived
             *     the same way: Meteroid's `remaining` when it supplies one, else `limit - consumed`,
             *     else `limit`. The two must agree — the SPA's usage bar reads this field and the `402`
             *     error body reads `QuotaSnapshot`, and a limited entitlement that reported a balance in
             *     one place and `null` in the other would make them contradict each other.
             */
            remaining: components["schemas"]["Decimal"] | null;
            /** @description Convenience mirror of `limit == null`. */
            unlimited: boolean;
            /**
             * Format: date-time
             * @description When the counter next resets. Null when Meteroid does not supply one.
             */
            reset_at: string | null;
            reset_period: components["schemas"]["ResetPeriod"];
            /**
             * @description Code of the billable metric this entitlement counts. Meteroid returns only a
             *     `metric_id`, so backends resolve it through a `metric_id` → `metric_code` map built once
             *     at startup from `GET /api/v1/metrics` and refreshed on a miss. Null when the metric
             *     cannot be resolved — this is deliberately not fatal, because the code is presentational
             *     (it lines entitlements up with `GET /api/usage`) and the quota check never uses it.
             * @example transcription_minutes
             */
            metric_code: string | null;
        };
        /** @description A static typed value — Scribe uses this for `retention_days` and `seats`. */
        ConfigEntitlementValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CONFIG";
            value: components["schemas"]["ConfigValue"];
        };
        /**
         * @description The three-way entitlement union, tagged by `type` exactly as Meteroid tags it. Clients
         *     switch on `type` and never guess from the shape.
         *
         *     As with `ConfigValue`, the tag is declared explicitly on each variant, so the union survives
         *     a strict internally-tagged deserializer even without discriminator support.
         */
        EntitlementValue: components["schemas"]["BooleanEntitlementValue"] | components["schemas"]["MeteredEntitlementValue"] | components["schemas"]["ConfigEntitlementValue"];
        Entitlement: {
            /**
             * @description The stable code the operator seeded. This is what application code gates on.
             * @example transcription_minutes
             * @example sso
             * @example retention_days
             * @example seats
             */
            feature_code: string;
            /** @example Transcription minutes */
            feature_name: string;
            value: components["schemas"]["EntitlementValue"];
        };
        EntitlementListResponse: {
            /**
             * @description One entry per feature the customer is entitled to, in the order Meteroid returned them.
             *     May be empty for a workspace with no subscription and no feature-level defaults.
             */
            entitlements: components["schemas"]["Entitlement"][];
        };
        CreateTranscriptionRequest: {
            /** @example Weekly standup */
            title: string;
            /**
             * Format: int32
             * @description Length of the (simulated) audio. Billed minutes are `duration_seconds / 60` rounded up
             *     to two decimals and reported to Meteroid as a decimal string.
             * @example 210
             */
            duration_seconds: number;
        };
        Transcription: {
            /** @example tr_01J9Z4X0000000000000000000 */
            id: string;
            title: string;
            /** Format: int32 */
            duration_seconds: number;
            /** @description Minutes reported to Meteroid for this transcription. */
            minutes_billed: components["schemas"]["Decimal"];
            /** @description The (simulated) transcript. The demo does no real speech recognition. */
            text: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description The `event_id` of the usage event ingested into Meteroid (max 255 characters there).
             *     Deterministic per transcription, which makes the ingest idempotent on retry.
             */
            event_id: string;
        };
        CreateTranscriptionResponse: {
            transcription: components["schemas"]["Transcription"];
            /**
             * @description The backend's projection of the metered entitlement after this call: the entitlement it
             *     read, minus the minutes it just billed. **Never null on a 201** — a request that got
             *     this far had a metered entitlement, since a missing or disabled one is a 403. An
             *     unlimited entitlement is reported with `unlimited: true` and null `limit`/`remaining`.
             *
             *     Meteroid's own counters are eventually consistent and may briefly disagree with this
             *     projection; `GET /api/usage` is the authority once it catches up.
             */
            quota: components["schemas"]["QuotaSnapshot"];
        };
        TranscriptionListResponse: {
            /** @description Newest first. In-memory only; empty after a backend restart. */
            transcriptions: components["schemas"]["Transcription"][];
        };
        GroupedUsage: {
            /** @description Segmentation keys and values for this slice. */
            dimensions: {
                [key: string]: string;
            };
            value: components["schemas"]["Decimal"];
        };
        /**
         * @description One metric's usage for the period. Meteroid's `MetricUsage` also carries `metric_id`, which
         *     the demo drops: `metric_code` is the stable identifier application code uses.
         */
        MetricUsage: {
            /** @example transcription_minutes */
            metric_code: string;
            metric_name: string;
            /** @description Total for the period. A decimal string, never a number. */
            total_value: components["schemas"]["Decimal"];
            /** @description Per-dimension breakdown. Empty when the metric has no segmentation. */
            grouped_usage: components["schemas"]["GroupedUsage"][];
        };
        UsageResponse: {
            /**
             * Format: date
             * @description Meteroid's `period_start` when `scope` is `subscription`; the first day of the current
             *     UTC calendar month when `scope` is `customer`.
             */
            period_start: string;
            /**
             * Format: date
             * @description Meteroid's `period_end` when `scope` is `subscription`; today (UTC) when `scope` is
             *     `customer`.
             */
            period_end: string;
            /**
             * @description Whether the period came from the workspace's subscription billing cycle or from the
             *     customer-wide fallback used when there is no subscription. The customer-scoped Meteroid
             *     endpoint requires an explicit date range, so a `customer` period is chosen by the demo,
             *     not by Meteroid.
             * @enum {string}
             */
            scope: "subscription" | "customer";
            metrics: components["schemas"]["MetricUsage"][];
        };
        /**
         * @description Optional in every sense: no body, an empty body, `{}`, and `{"expires_in_seconds": null}`
         *     all mean "use the default".
         */
        CreatePortalSessionRequest: {
            /**
             * Format: int32
             * @description Token lifetime. Meteroid documents 60..2592000 and defaults to 86400. Values outside
             *     that range are rejected here with `BAD_REQUEST` rather than forwarded.
             */
            expires_in_seconds?: number | null;
        };
        CreatePortalSessionResponse: {
            /**
             * Format: uri
             * @description Base URL of the Meteroid customer portal.
             */
            portal_url: string;
            /** @description Short-lived JWT granting portal access for this workspace's customer. */
            token: string;
            /**
             * Format: int32
             * @description The lifetime the backend requested (the request value, or 86400). Meteroid returns only
             *     `{ token, portal_url }`, so this is echoed, not read back from the token.
             */
            expires_in_seconds: number;
        };
        /**
         * @description Mirrors Meteroid's invoice status enum.
         * @enum {string}
         */
        InvoiceStatus: "DRAFT" | "FINALIZED" | "UNCOLLECTIBLE" | "VOID" | "CLOSED";
        /**
         * @description Invoice summary. `total` and `amount_due` are integers in the currency's **minor units**
         *     (cents) — Meteroid models invoice money as an integer, not as a decimal, and this contract
         *     does not convert. This is the one place the decimals-are-strings rule does not apply; do not
         *     "fix" it for consistency.
         *
         *     Meteroid currently types these as `int32`; the contract widens them to `int64` so a future
         *     Meteroid widening does not become a breaking change here. Backends widen on the way out.
         */
        Invoice: {
            id: string;
            invoice_number: string;
            status: components["schemas"]["InvoiceStatus"];
            currency: components["schemas"]["Currency"];
            /**
             * Format: date
             * @description Meteroid's `invoice_date` — the emission date.
             */
            invoice_date: string;
            /**
             * Format: date
             * @description Null when the invoice has no due date (net terms 0, or a draft).
             */
            due_date: string | null;
            /**
             * Format: int64
             * @description Invoice total in minor units.
             */
            total: number;
            /**
             * Format: int64
             * @description Outstanding amount in minor units.
             */
            amount_due: number;
        };
        InvoiceListResponse: {
            /** @description Newest first. */
            invoices: components["schemas"]["Invoice"][];
        };
        /**
         * @description A Meteroid webhook envelope. Meteroid owns this shape, adds event types over time, and —
         *     importantly — **publishes no schema for it**: webhook payloads do not appear anywhere in
         *     `spec/openapi.json`, because endpoints are configured in the dashboard.
         *
         *     So this is the one schema in the contract that stays open *and* has no required properties.
         *     The three properties below are the demo's best-effort expectation, not a verified contract.
         *     A receiver reads what it recognizes and acknowledges everything else; it must never reject a
         *     correctly signed body because a property is missing or unexpected. Treat this schema as
         *     documentation of intent, and the signature as the actual gate.
         */
        MeteroidWebhookEvent: {
            /** @description Meteroid event id, if present. Falls back to the `webhook-id` header. */
            id?: string | null;
            /**
             * @description Dotted event type, e.g. `invoice.paid`, `subscription.created`. Not an enum here on
             *     purpose — a receiver must not break when Meteroid adds a type. Null when the payload
             *     carries no recognizable type, which is acknowledged with `handled: false`.
             * @example invoice.paid
             * @example subscription.created
             */
            type?: string | null;
            /**
             * Format: date-time
             * @description Event time, if present. Not to be confused with the `webhook-timestamp` header.
             */
            timestamp?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Acknowledgement of a signed event. A 202 means "signature verified and body accepted", not
         *     "the demo understood it" — that is what `handled` is for.
         */
        WebhookAck: {
            /** @constant */
            received: true;
            /**
             * @description The event's `id`, or the `webhook-id` header when the body carries none. Never null:
             *     `webhook-id` is a required header, so there is always a value to echo.
             */
            event_id: string;
            /** @description The body's `type`, or null when it carries none. */
            type: string | null;
            /**
             * @description True when the demo has a handler for this event type (`invoice.*`, `subscription.*`).
             *     False means acknowledged and ignored — never an error, and the only outcome for a
             *     payload with an unknown or absent `type`.
             */
            handled: boolean;
        };
    };
    responses: {
        /** @description The request body or query is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The session token is missing, malformed, or not signed by this deployment. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Meteroid throttled the backend (it returns `429` on every endpoint this demo calls) or the
         *     backend is throttling itself. Retry after a short backoff; the demo does not add a
         *     `Retry-After` header.
         */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description An unhandled failure in the demo backend itself — a bug, not a Meteroid or configuration
         *     problem. Declared on every operation so the contract suite validates the envelope instead of
         *     hitting an untyped framework error page.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The metered entitlement's remaining balance is smaller than the requested amount. The body
         *     carries the live quota snapshot and the plan the frontend should offer as an upgrade.
         */
        QuotaExhausted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The workspace's plan does not grant the feature at all, or the entitlement is explicitly
         *     disabled. Distinct from `QUOTA_EXHAUSTED`, which means "granted, but used up".
         */
        FeatureNotEntitled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The Meteroid API returned an error or was unreachable. `UPSTREAM_UNAUTHORIZED` specifically
         *     means the backend's `METEROID_API_KEY` is missing, wrong, or revoked — an operator problem.
         */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A catalog object this demo requires is missing from the Meteroid tenant. The demo never
         *     creates catalog objects — see `examples/CATALOG.md` and seed them once in the dashboard.
         *     The message always names the missing object using the exact identifier the backend looked up.
         */
        CatalogNotSeeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The backend is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Workspace created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["CatalogNotSeeded"];
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pricing table. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["CatalogNotSeeded"];
        };
    };
    createCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutRequest"];
            };
        };
        responses: {
            /** @description Checkout session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCheckoutResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description Checkout cannot be started for this workspace and plan — for example the workspace is
             *     already subscribed to the requested plan version.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["CatalogNotSeeded"];
        };
    };
    listEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective entitlements. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    listTranscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTranscriptionRequest"];
            };
        };
        responses: {
            /** @description Transcribed, and the consumed minutes were reported to Meteroid. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTranscriptionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExhausted"];
            403: components["responses"]["FeatureNotEntitled"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["CatalogNotSeeded"];
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage for the current period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    createPortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreatePortalSessionRequest"];
            };
        };
        responses: {
            /** @description Portal token minted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePortalSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                /** @description Maximum number of invoices to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    receiveMeteroidWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique message id. `svix-id` is accepted as an alias. */
                "webhook-id": string;
                /** @description Unix seconds. `svix-timestamp` is accepted as an alias. */
                "webhook-timestamp": string;
                /** @description Space-separated list of `v1,<base64>` signatures. `svix-signature` is accepted as an alias. */
                "webhook-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeteroidWebhookEvent"];
            };
        };
        responses: {
            /** @description Signature verified and the event was accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /**
             * @description The signature is missing, malformed, expired, or does not match the raw body; or the
             *     body is not a Meteroid event envelope.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
