# build openapi-codegen
FROM docker.io/lukemathwalker/cargo-chef:latest-rust-1.88 AS chef
WORKDIR /app

FROM chef AS planner

COPY Cargo.toml .
COPY Cargo.lock .
COPY src /app/src

RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS openapi-codegen-builder

COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --release --recipe-path recipe.json

COPY Cargo.toml .
COPY Cargo.lock .
COPY src /app/src

RUN cargo build --release --bin openapi-codegen


# download java formatter
FROM alpine:3.21 AS javafmt-downloader
ARG JAVAFMT_DL_LINK="https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format-native/2.75.0/palantir-java-format-native-2.75.0-nativeImage-linux-glibc_x86-64.bin"
ARG JAVAFMT_SHA256="9d8c9e65cff44bb847d16b4db2ccbd6dacbe32611eaf2587748013eda931cdac"
RUN apk add --no-cache curl binutils coreutils
RUN echo "${JAVAFMT_SHA256} palantir-java-format.bin" > palantir-java-format.bin.sha256 && \
    curl -fsSL --output palantir-java-format.bin "${JAVAFMT_DL_LINK}" && \
    sha256sum palantir-java-format.bin.sha256 -c && \
    mv palantir-java-format.bin /usr/bin && \
    chmod +x /usr/bin/palantir-java-format.bin


# main image
FROM alpine:3.21
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin"
RUN apk add --no-cache openjdk17-jre-headless curl gcompat libgcc libstdc++

# Java formatter
RUN echo "25157797a0a972c2290b5bc71530c4f7ad646458025e3484412a6e5a9b8c9aa6 google-java-format-1.25.2-all-deps.jar" > google-java-format-1.25.2-all-deps.jar.sha256 && \
    curl -fsSL --output google-java-format-1.25.2-all-deps.jar "https://github.com/google/google-java-format/releases/download/v1.25.2/google-java-format-1.25.2-all-deps.jar" && \
    sha256sum google-java-format-1.25.2-all-deps.jar.sha256 -c && \
    rm google-java-format-1.25.2-all-deps.jar.sha256 && \
    mv google-java-format-1.25.2-all-deps.jar /usr/bin/  && \
    echo "#!/bin/sh" >> /usr/bin/google-java-format && \
    echo '/usr/bin/java -jar /usr/bin/google-java-format-1.25.2-all-deps.jar $@' >> /usr/bin/google-java-format && \
    chmod +x /usr/bin/google-java-format


# TypeScript/JavaScript formatter (biome)
ARG BIOME_DL_LINK="https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.1.4/biome-linux-x64-musl"
ARG BIOME_SHA256="6d6bd2213cffab0d68d741c0be466bcd21cd6f5eca1e0e5aac2a991bf9f17cf2"
RUN echo "${BIOME_SHA256} biome" > biome.sha256 && \
    curl -fsSL --output biome "${BIOME_DL_LINK}" && \
    sha256sum biome.sha256 -c && \
    rm biome.sha256 && \
    mv biome /usr/bin/  && \
    chmod +x /usr/bin/biome

# Rust formatter (rustfmt)
# Minimal install to reduce image size
RUN apk add --no-cache binutils && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
    -y \
    --profile minimal \
    --no-modify-path \
    --no-update-default-toolchain \
    --default-toolchain nightly-2025-02-27 \
    --component rustfmt && \
    rm -rf /root/.rustup/toolchains/nightly-*/lib/rustlib && \
    rm /root/.rustup/toolchains/nightly-*/bin/cargo* && \
    rm /root/.rustup/toolchains/nightly-*/bin/rust-* && \
    rm /root/.rustup/toolchains/nightly-*/bin/rustc && \
    rm /root/.rustup/toolchains/nightly-*/bin/rustdoc && \
    rm -rf /root/.rustup/toolchains/nightly-*/share && \
    strip /root/.rustup/toolchains/nightly-*/lib/librustc_driver-*.so && \
    apk del binutils

# Java formatter for code samples (palantir)
COPY --from=javafmt-downloader /usr/bin/palantir-java-format.bin /usr/bin/palantir-java-format.bin

# openapi-codegen
COPY --from=openapi-codegen-builder /app/target/release/openapi-codegen /usr/bin/
