// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// CreatePlanRequest is the CreatePlanRequest object of the Meteroid API.
type CreatePlanRequest struct {
	AddOns []PlanAddOnInput `json:"add_ons,omitempty"`

	Billing *BillingConfig `json:"billing,omitempty"`

	Components RequiredSlice[PriceComponentInput] `json:"components"`

	Currency string `json:"currency"`

	Description *string `json:"description,omitempty"`

	Name string `json:"name"`

	PlanType PlanTypeEnum `json:"plan_type"`

	ProductFamilyID ProductFamilyID `json:"product_family_id"`

	SelfServiceRank *int32 `json:"self_service_rank,omitempty"`

	Status PlanStatusEnum `json:"status"`

	Trial *TrialConfig `json:"trial,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *CreatePlanRequest) UnmarshalJSON(data []byte) error {
	type plain CreatePlanRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "add_ons", "billing", "components", "currency", "description", "name", "plan_type", "product_family_id", "self_service_rank", "status", "trial")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v CreatePlanRequest) MarshalJSON() ([]byte, error) {
	type plain CreatePlanRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
