// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// FeaturesListOptions carries the optional query and header parameters of
// [Features.List]. Leave a field nil to omit it.
type FeaturesListOptions struct {
	// Filter by feature status. Repeat the param to select multiple, omit to return all.
	Statuses []FeatureStatus

	// Filter by product. Omit to return features across all products.
	ProductID *ProductID

	// Search by feature name.
	Search *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// Features groups the features operations of the Meteroid API.
type Features struct {
	client *Client
}

// List features
func (a *Features) List(ctx context.Context, options *FeaturesListOptions, opts ...RequestOption) (*FeatureListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/features", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && len(options.Statuses) > 0 {
		for _, item := range options.Statuses {
			req.AddQueryParam("statuses", formatValue(item))
		}
	}
	if options != nil && options.ProductID != nil {
		req.SetQueryParam("product_id", formatValue(*options.ProductID))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out FeatureListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/features/{id_or_code}.
//
// Get feature details
func (a *Features) Retrieve(ctx context.Context, idOrCode string, opts ...RequestOption) (*Feature, error) {
	req := newRequest(http.MethodGet, "/api/v1/features/{id_or_code}", opts)
	req.SetPathParam("id_or_code", idOrCode)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out Feature
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
