// Code generated by perseid. DO NOT EDIT.

package meteroid_test

import (
	"testing"
)

func TestFeatures_List(t *testing.T) {
	client, requests := mock(200, "application/json", `{"data":[{"code":"sample","created_at":"2023-12-31T23:59:59.999-05:30","feature_type":{"type":"BOOLEAN"},"id":"feature_id_0","name":"sample","status":"DISABLED"}],"pagination_meta":{"page":-123456789,"per_page":-123456789,"total_items":-9007199254740993,"total_pages":123456789}}`)
	call(t, client.Features().List, nil)
	expect(t, requests, "GET /api/v1/features")
}

func TestFeatures_Retrieve(t *testing.T) {
	client, requests := mock(200, "application/json", `{"code":"sample","created_at":"2024-03-15T10:30:45.123+02:00","feature_type":{"type":"BOOLEAN"},"id":"feature_id_90","name":"sample","status":"ARCHIVED"}`)
	call(t, client.Features().Retrieve, "id_or_code")
	expect(t, requests, "GET /api/v1/features/id_or_code")
}
