// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"context"
	"net/http"
)

// ProductsListOptions carries the optional query and header parameters of
// [Products.List]. Leave a field nil to omit it.
type ProductsListOptions struct {
	ProductFamilyID *ProductFamilyID

	Search *string

	// Sort order. Format: `column.direction`. Allowed columns: `name`, `created_at`. Direction: `asc` or `desc`. Default: `name.asc`.
	OrderBy *string

	// Page number (0-indexed)
	Page *int32

	// Number of items per page
	PerPage *int32
}

// Products groups the products operations of the Meteroid API.
type Products struct {
	client *Client
}

// List products
func (a *Products) List(ctx context.Context, options *ProductsListOptions, opts ...RequestOption) (*ProductListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/products", opts)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	if options != nil && options.ProductFamilyID != nil {
		req.SetQueryParam("product_family_id", formatValue(*options.ProductFamilyID))
	}
	if options != nil && options.Search != nil {
		req.SetQueryParam("search", *options.Search)
	}
	if options != nil && options.OrderBy != nil {
		req.SetQueryParam("order_by", *options.OrderBy)
	}
	if options != nil && options.Page != nil {
		req.SetQueryParam("page", formatInt(int64(*options.Page)))
	}
	if options != nil && options.PerPage != nil {
		req.SetQueryParam("per_page", formatInt(int64(*options.PerPage)))
	}
	var out ProductListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a product
func (a *Products) Create(ctx context.Context, createProductRequest CreateProductRequest, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodPost, "/api/v1/products", opts)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(createProductRequest)
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve sends GET /api/v1/products/{product_id}.
//
// Get product details
func (a *Products) Retrieve(ctx context.Context, productID string, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodGet, "/api/v1/products/{product_id}", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a product
//
// Partially update product fields. The fee_type is immutable and cannot be changed.
func (a *Products) Update(ctx context.Context, productID string, updateProductRequest UpdateProductRequest, opts ...RequestOption) (*Product, error) {
	req := newRequest(http.MethodPatch, "/api/v1/products/{product_id}", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"400": errorSchema[RestErrorResponse],
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	req.SetJSONBody(updateProductRequest)
	var out Product
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Archive a product
func (a *Products) Archive(ctx context.Context, productID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/products/{product_id}/archive", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}

// ListEntitlements sends GET /api/v1/products/{product_id}/entitlements.
//
// List product entitlements
func (a *Products) ListEntitlements(ctx context.Context, productID string, opts ...RequestOption) (*ResolvedEntitlementListResponse, error) {
	req := newRequest(http.MethodGet, "/api/v1/products/{product_id}/entitlements", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	var out ResolvedEntitlementListResponse
	if err := a.client.execute(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Unarchive a product
func (a *Products) Unarchive(ctx context.Context, productID string, opts ...RequestOption) error {
	req := newRequest(http.MethodPost, "/api/v1/products/{product_id}/unarchive", opts)
	req.SetPathParam("product_id", productID)
	req.errors = errorSchemas{
		"401": errorSchema[RestErrorResponse],
		"404": errorSchema[RestErrorResponse],
		"429": errorSchema[RestErrorResponse],
	}
	return a.client.execute(ctx, req, nil)
}
