// Code generated by perseid. DO NOT EDIT.

package meteroid

import "encoding/json"

// ReplacePlanRequest is the ReplacePlanRequest object of the Meteroid API.
type ReplacePlanRequest struct {
	AddOns []PlanAddOnInput `json:"add_ons,omitempty"`

	Billing *BillingConfig `json:"billing,omitempty"`

	Components RequiredSlice[PriceComponentInput] `json:"components"`

	Currency string `json:"currency"`

	Description *string `json:"description,omitempty"`

	MinimumCommitment *MinimumCommitmentInput `json:"minimum_commitment,omitempty"`

	Name string `json:"name"`

	Status *PlanStatusEnum `json:"status,omitempty"`

	Trial *TrialConfig `json:"trial,omitempty"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *ReplacePlanRequest) UnmarshalJSON(data []byte) error {
	type plain ReplacePlanRequest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "add_ons", "billing", "components", "currency", "description", "minimum_commitment", "name", "status", "trial")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v ReplacePlanRequest) MarshalJSON() ([]byte, error) {
	type plain ReplacePlanRequest
	return marshalWithExtra(plain(v), v.ExtraFields)
}
