// Code generated by perseid. DO NOT EDIT.

package meteroid

import (
	"encoding/json"
	"time"
)

// Transaction is the Transaction object of the Meteroid API.
type Transaction struct {
	Amount int64 `json:"amount"`

	Currency string `json:"currency"`

	Error *string `json:"error,omitempty"`

	ID PaymentTransactionID `json:"id"`

	PaymentMethodID *CustomerPaymentMethodID `json:"payment_method_id,omitempty"`

	PaymentMethodInfo *PaymentMethodInfo `json:"payment_method_info,omitempty"`

	PaymentType PaymentTypeEnum `json:"payment_type"`

	// RFC 3339 timestamp.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	ProviderTransactionID *string `json:"provider_transaction_id,omitempty"`

	Status PaymentStatusEnum `json:"status"`

	// ExtraFields holds the properties this SDK version does not know, as
	// decoded, and sends them along when encoding.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON implements json.Unmarshaler, keeping unknown properties in ExtraFields.
func (v *Transaction) UnmarshalJSON(data []byte) error {
	type plain Transaction
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	v.ExtraFields = extraFields(data, "amount", "currency", "error", "id", "payment_method_id", "payment_method_info", "payment_type", "processed_at", "provider_transaction_id", "status")
	return nil
}

// MarshalJSON implements json.Marshaler, sending ExtraFields along.
func (v Transaction) MarshalJSON() ([]byte, error) {
	type plain Transaction
	return marshalWithExtra(plain(v), v.ExtraFields)
}
