name: Mega Releaser

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".version"

jobs:
  kick-off:
    name: Kick-off Releases
    runs-on: ubuntu-latest
    steps:
      - run: /bin/true
